version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: aplicacao
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  mysql_data:
  es_data: